title: Cofre do José
author: 
    name: José Clementino
    e-mail: jclmntn@gmail.com
description: 
    Alguns dos meus projetos em programação e análise de dados. Todos feitos durante minhas horas vagas (ou não).

github_username: jclmntn
linkedin_username: jclmntn

header_pages:
  - about.md
  
theme: minima
