title: Depósito do José 
author: José Clementino
email: "jclmntn@gmail.com"
description: 
    Alguns dos meus projetos em programação e análise de dados. Todos feitos durante minhas horas vagas (ou não).

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/jclmntn"}
    - { platform: github, user_url: "https://linkedin.com/in/jclmntn"}
  skin: dark

header_pages:
  - about.md


remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

