title: Cofre do José
author:
  name: José Clementino
  email: jclmntn@gmail.com
description: 
    Alguns dos meus projetos em programação e análise de dados. Todos feitos durante minhas horas vagas (ou não).

github_username: jclmntn
linkedin_username: jclmntn

header_pages:
  - about.md


remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

