title: Cofre do José
author:
  name: José Clementino
  email: jclmntn@gmail.com
description: 
    Alguns dos meus projetos em programação e análise de dados. Todos feitos durante minhas horas vagas (ou não).

minima:
  date_format: "%-d %b, %Y"
  skin: dark
  
header_pages:
  - about.md
  
theme: minima
