title: Cofre do José 
author: José Clementino
e-mail: "jclmntn@gmail.com"
description: 
    Alguns dos meus projetos em programação e análise de dados. Todos feitos durante minhas horas vagas (ou não).

minima:
  social_links:
    github: jclmntn
    linkedin: jclmntn
  skin: dark

header_pages:
  - about.md


remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

