title: Your awesome title
author:
  name: jclmntn
  email: jclmntn@gmail.com
description: 
    Algumas das minhas aventuras em programação e análise de dados. Todas foram feitas durante minhas horas vagas.

minima:
  date_format: "%-d %b, %Y"
  skin: dark
